# Generated by Django 5.0.7 on 2024-07-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('Livro', 'Livro'), ('Manga', 'Manga'), ('LightNovel', 'LightNovel'), ('Novel', 'Novel'), ('HQ', 'HQ')], default=None, max_length=20),
        ),
    ]
