# Generated by Django 5.0.7 on 2024-07-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('contry_origin', models.CharField(choices=[('USA', 'Estados Unidos'), ('BR', 'Brasil'), ('FRA', 'França'), ('JP', 'Japão'), ('DE', 'Alemanha')], max_length=4)),
            ],
        ),
    ]
