# Generated by Django 5.0.7 on 2024-07-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='contry_origin',
            field=models.CharField(choices=[('USA', 'Estados Unidos'), ('BR', 'Brasil'), ('FRA', 'França'), ('JP', 'Japão'), ('DE', 'Alemanha'), ('ITA', 'Itália')], max_length=4),
        ),
    ]
